### ISSUE TITLE
Error in namespace parsing

### ISSUE THREAD

**Issue by chrmor** [DM2E/dm2e-mappings#1]
Link: http://data.dm2e.eu/data/html/list
Question marks in place of URL prefixes usually denotes some mulfunctioning (e.g. ?:hasCollection)

Link: http://data-worker.dm2e.hu-berlin.de/data/html/resourcemap/bbaw/dta/16157/1391002599515
a namespace is broken : ?:author (http://purl.org/spar/pro/author)

**Comment by kba** [comment]
Fixed.
