### ISSUE TITLE
Are unknown properties errors?

### ISSUE THREAD

**Issue by kba** [DM2E/dm2e-mappings#10]
Should the validation rely on a strict closed world assumption and consider properties that are not defined by the DM2E data model as an error or a mere warning?

Right now, I collect all DatatypeProperties and ObjectProperties of the resp. OWL file and iterate through all the properties in the data to check. If a property is not in this _whitelist_, a WARNING is given.

But in most cases, these are actually errors, e.g.

```
<http://data.dm2e.eu/data/item/mpiwg/harriot/MPIWG:01QU84RT_982>:.
    [WARNING]   UNKNOWN_PROPERTY    http://purl.org/dc/terms/description
    [WARNING]   UNKNOWN_PROPERTY    http://purl.org/ontology/bibo/number/
    [WARNING]   UNKNOWN_PROPERTY    http://purl.org/dc/terms/title
```

1 and 3 should be dc elements not dcterms, 2 is a typo.

So I suggest making unknown properties errors.

**Comment by ksdm2e** [comment]
That's an error. It must be corrected by the dataprovider.

**Comment by kba** [comment]
Are errors now.
