### ISSUE TITLE
dm2e:copyist as a subclass of dc:creator?

### ISSUE THREAD

**Issue by kba** [DM2E/dm2e-mappings#108]
@knepper proposed to subclass dm2e:copyist to dc:creator instead of the more generic edm:hasMet. An alternative would be to subclass dm2e:copyist to dc:contributor.

**Comment by edroege** [comment]
I would prefer to make it a subproperty of dc:contributor because someone who copied a CHO has not necessarily created it.

**Comment by knepper** [comment]
I agree to @edroege.

**Comment by kba** [comment]
+1 for dc:contributor

**Comment by edroege** [comment]
Changed in model version 1.2 revision 1
