### ISSUE TITLE
dm2e:holdingInstitution should be subProperty of edm:currentLocation

### ISSUE THREAD

**Issue by d0rg0ld** [DM2E/dm2e-mappings#110]
dm2e:holdingInstitution is currently a subProp of edm:hasMet, I suggest it to be changed to be a subProperty of edm:currentLocation (http://europeana.ontotext.com/resource/edm/currentLocation) : The geographic location and/or name of the repository, building, site, or other entity whose boundaries presently include the resource.@en

**Comment by edroege** [comment]
This is not possible: the range of dm2e:holdingInstitution is foaf:Organization, the range of edm:currentLocation is edm:Place.

**Comment by d0rg0ld** [comment]
Ok, that's a pity. Related to the other proposal with dc:contributor" the main reason is again that this information will be mapped to the generic edm:hasMet, unifying very different agent<->CHO relationships under one broad umbrella term
