### ISSUE TITLE
Move additional properties from having edm:hasMet to dc:contributor as superProperty

### ISSUE THREAD

**Issue by d0rg0ld** [DM2E/dm2e-mappings#111]
I suggest additional changes to the superproperties of the following dm2e props:

dm2e:sponsor
dm2e:principal
bibo:editor
pro:printer

they all should become subproperties of dc:contributor

**Comment by edroege** [comment]
Depends maybe on the definition of contributor. Is a printer or a sponsor really contributing to a CHO? We (and DC :) ) have a very broad definition of contributor: "A person that is responsible for making contributions to the resource." but even with that broad definition I would e.g. not want to say that the printer of Dingler has made a contribution to the actual CHO. Contributors are in my point of view e.g. persons who have actually created parts of the CHO like an illustration etc. but not someone who printed or sponsored the work. In that logic, the EU would be contributing to the DM2E model ;) This is not exactly true.

But this is only my opinion. Would be interested to know what the others think.

Editor is different but it depends on the CHO if the editor has really contributed something I guess.

**Comment by d0rg0ld** [comment]
Well, at least regarding sponsor or principal I would argue that they made a significant (financial) contribution to the creation of the resource. With printer I think it's more difficult, but given the DM2E definition "A person or institution who printed the CHO. In the manuscript context especially used in works of the 16th and 17th century (rare books)." I'd rather tend to see him/her as a contributor. But, of course, it's also only my opinion.

The main reason for me to propose the rearrangment of these properties is that I think that we lose a lot of information by mapping all these to the ultra-generic edm:hasMet.

**Comment by edroege** [comment]
I totally understand you - edm:hasMet is very generic. My concern is only that we would in the other way produce a lot of data that may not be totally correct when mapping DM2E data back to EDM

**Comment by d0rg0ld** [comment]
This is indeed a problem. Probably we should try to find out how dc:contributor is used across Europeana?

**Comment by kba** [comment]
I think it's better to possibly not be 100 percent semantically accurate and have the data visible and usable rather than the opposite. So +1 for subclassing.

**Comment by kba** [comment]
Problem: dc:contributor is defines as having range foaf:Person, while dm2e:sponsor, dm2e:principal and pro:printer have range edm:Agent. Subclassing these properties as is to dc:contributor will lead to logical contradictions.

We can either narrow the ranges of these properties or of dc:contributor. I don't remember the reasoning behind limiting dc:contributor in the DM2E AP to foaf:Person but the official definition ("An entity responsible for making contributions to the resource. [...] Examples of a Contributor include a person, an organization, or a service.") would certainly allow it to broaden the range to edm:Agent.

**Comment by knepper** [comment]
dc:contributor should be edm:Agent. Otherwise we get Problems with the mapping of library catalogue data where we cannot always distinguish between organisations and persons. And if - where else shall we map contributing organisations?

I think bibo:editor is already defined as a subproperty of dc:contributor? I tend to include also dm2e:sponsor and dm2e:principal to dc:contributor because it keeps always connected to the work. But pro:printer has a role like a publisher and in library context this is usually considered to be different from a contributor. Imagine another edition or reprint of a work: The printer/publisher may change but all contributers should stay the same.

**Comment by d0rg0ld** [comment]
Hi

Here a little bump to the DM2E ontology discussion: After a talk with SBB, I think we will have to change the superproperty of dm2e:holdingInstitution. It currently mapped to edm:hasMet, which is far to generic in my opinion. Therefore. lacking anything more useful, I suggest to use dcterms:provenance as superproperty instead.

@edroege @kba @JIwanowa  please let me know what you think about it.

Thanks,
Doron

**Comment by knepper** [comment]
I think its reasonable. But what is the effect - why did you think about it with SBB?

**Comment by d0rg0ld** [comment]
because they claimed the holdingInstitution property since they're hosting digital items for third parties who would like to be acknowledged accordingly. EDM does not really provide such a prop, so dcterms:provenance seems to be the right choice to me

**Comment by d0rg0ld** [comment]
very related to this is a bug in the DM2E-EDM mapping where dcterms:provenance does not get into the EDM output (https://github.com/DM2E/dm2e-ontologies/issues/4)

**Comment by JIwanowa** [comment]
Hi, 

the problem is that the dm2e:holdingInstitution is an object property and the dcterms:provenance is a data type property. To be consistent, we've defined therefore edm:hasMet as super property of dm2e:holdingInstitution.

**Comment by d0rg0ld** [comment]
I see. but hasMet is too generic and does currently not display in Europeana. SBB demands the holdingInstitution to be visible in the Europeana display. Therefore we need to find a way to make it possible. What about allowing literals in dm2e:holdingInstitution as well? doesnt it become a data type property then?

**Comment by JIwanowa** [comment]
If we do so, then we have to change the super property to dcterms:provenance and the range of dm2e:holdingInstitution should be rdf:Literal or/and foaf:Organization. I think we should also be aware which kind of data type (literals or resources) Europeana will be able to handle. Depends on it, we can also think about the possibility to map the dm2e:holdingInstition property to dcterms:provenance during the mapping from DM2E to EDM. What do you think?

**Comment by d0rg0ld** [comment]
Hi, thanks, I checked the EDM docs and http://old.europeanalabs.eu/wiki/EDMObjectTemplatesProviders says for dcterms:provenance:

dcterms:provenance  literal or reference    min 0, max unbounded

so it should IMHO be possible to extend the range of dm2e:holdingInstitution and move it under dcterms:provenance ...

**Comment by JIwanowa** [comment]
ok. thanks! I'll change the range and the super property from dm2e:holdingInstitution!

**Comment by d0rg0ld** [comment]
great, thx, so now we will just have to fix (DM2E/dm2e-ontologies#4)

**Comment by edroege** [comment]
Hi!
@d0rg0ld: almost everything in EDM has the range literal or reference :) A thing that we tried to avoid in our model. We had problems producing a proper owl file if we have that mixes and tried to avoid them. 
All: would it be a solution to just have the range literal _only_ and thus making dcterms:provenance a datatype property? I wanted to adjust the owl file at https://github.com/DM2E/dm2e-ontologies/blob/master/src/main/resources/dm2e-model/DM2Ev1.2-rc2.owl but am also unsure how to do it if we mix literals and resources in property ranges. We should really not do that if we can avoid it.

**Comment by JIwanowa** [comment]
Hi @edroege, I agree with you that mixed ranges are not good solution, but I also don't like the option to remove the resources at all, because we could lost additional data about the institutions it self. I am still thinking about the possibility to map the rdf:label from foaf:Organisation by dm2e:holdingInstitution in to dcterms:provenance during the backward mapping to EDM. @kba what do you think? Is this possible? That way we will keep the DM2E model consistent without loss of information, I think.

**Comment by d0rg0ld** [comment]
Hi,
I understand your objection, @edroege . AFAIK, only SBB use holdingInstitution and currently put a foaf:Organization there. I guess it should be manageable to replace this with a string. But I also like @JIwanowa 's suggestion to "downgrade" from resource to literal during dm2e-edm transformation. @kba will know better, but I guess it should be possible - at least as hard-coded directive. I dont know, however, how to model this in the owl file.

**Comment by JIwanowa** [comment]
Hi,
if we go on with the DM2E to EDM-Mapping solution we don't need to change the DM2E model, respectively to remodel the owl file.

**Comment by knepper** [comment]
In the METS/MODS mapping I have a parameter switch that allows to use the data provider resource for the holdinginstition - which is the case for the ubffm data. The result is a foaf:Organization for holdinginstituion like SBB.

**Comment by kba** [comment]
Hi y'all, using the skos:prefLabel of the agent linked by dm2e:holdingInstitution in the DM2E version as the literal value of dcterms:provenance in the EDM version is possible.

```
dm2edata:someCHO holdingInstutition dm2edata:SBB .
dm2edata:SBB skos:prefLabel "Staatsbibliothek zu Berlin" .
```

would become

```
dm2edata:someCHO dcterms:provenance "Staatsbibliothek zu Berlin"
```

It's not the cleanest solution semantics-wise, but if there is no other EDM property that conveys the meaning of holdingInstitution, allows a range of agents/persons/organizations and is properly displayed in the Portal, this is the next best fix that won't require a change to the models.
