### ISSUE TITLE
foaf:Organization subclasses

### ISSUE THREAD

**Issue by edroege** [DM2E/dm2e-mappings#112]
Is anyone attending to use subclasses of foaf:Organization or has used them since our model evaluation?

foaf:Organization subclasses:
dm2e:Archive
vivo:Library
vivo:Museum
vivo:University

Do we need such subclasses? A short message would be great :)

**Comment by ksdm2e** [comment]
Unfortunately, we can't specialize our Organizations automatically because there are no indicators in the data.

**Comment by knepper** [comment]
It could be used for edm:dataprovider but I don't think that it is really needed. Our library ist part of a university and there is also an archive part of our library. Almost all of the subclasses listed would match :-)

**Comment by edroege** [comment]
The classes will be removed in the last model version
