### ISSUE TITLE
How to find the annotatable version and facsimile image?

### ISSUE THREAD

**Issue by kba** [DM2E/dm2e-mappings#12]
If I encounter a CHO with `dm2e:displayLevel "true"^^xsd:boolean` whose corresponding `ore:Aggregation` has neither `edm:isShownBy`, `edm:object` nor `dm2e:hasAnnotatableVersion`, what should be displayed as
- the annotatable version
- the thumbnail?

Should I skip those links altogether?

Should I select the first page for annotation/as thumbnail? How do I find the first page?

**Comment by kba** [comment]
The SPARQL I use for the first page currently:

```
SELECT DISTINCT ?cho WHERE {
   ?cho dcterms:isPartOf* ?parentCHO .
   FILTER(?cho != ?parentCHO)
   ?agg edm:aggregatedCHO ?cho .
   ?agg dc:type dm2e:Page
} ORDER BY STR(?cho) LIMIT 1
```

**Comment by d0rg0ld** [comment]
For now I would display a default icon/thumbnail, probably based on the dc:type of the CHO

**Comment by edroege** [comment]
In my opinion, a default icon should only be used if everything else does not work. Otherwise we will have so many identical thumbnails that showing a thumbnail does not add any value.

**Comment by d0rg0ld** [comment]
ok, lets make it more precise:

for a CHO with displayLevel=true, i suggest the following steps:

1) Is it a page CHO? (Should not happen btw)

```
    Does it have edm:Object set? 
        If yes, go for it; break
    Does it have hasAnnotatableVersion set? 
        If yes, check the dc:format of the connected WebResource, 
               If it is an Image file --> go for it; break
```

2) It is NOT a page CHO (This will be the regular case)

```
     Does it have edm:Object set? 
        If yes, go for it; break
     Does it have page CHOs beneath?
        If yes, pick the one with bibo:number=1 :-) and goto step 1)
```

3) If  neither step 1) or 2) result in a usable Image

```
     Use a Default thumbnail
```

**Comment by kba** [comment]
For now, querying for edm:object/dm2e:hasAnnotatableVersion/edm:isShownBy with appropriate dc:format works well enough, for the non-matches provide default per-dc:type thumbnail.
