### ISSUE TITLE
dm2e:genre should not be a subtype of dc:description

### ISSUE THREAD

**Issue by kba** [DM2E/dm2e-mappings#14]

**Comment by ksdm2e** [comment]
I vote from the beginning for 

subtype from dc:type.

It actually should override dc:type.

**Comment by kba** [comment]
It currently is both a subtype of dc:type and dc:description. But the latter makes no sense and should be taken out.

What do you mean with 'override'?

**Comment by ksdm2e** [comment]
type is very technical term; technic in sense of electronic documents and dublin core background. Archivist, librarians and linguists prefer the term "genre".

If you see DM2E as a model for describing manuscripts, genre is more appropriate for archival description (compare: genre in EAD).

I mean with "override": in DM2E dc:type should be forbidden, but dm2e:genre should be used instead.

**Comment by kba** [comment]
Discouraging the use of dc:type in the validator is straightforward, I can do that. But it should be merely a warning. I don't have an example myself, but I can imagine that providers might specify the type of a manuscript beyond it's genre. In that case we should add additional subclasses though.

**Comment by ksdm2e** [comment]
I guess this should be decided by the data model maintenance task force. I would leave it as it is, but cut dc:description as superclass.

**Comment by edroege** [comment]
dc:type is crucial as it is used to indicate the type of the CHO like page, article and so on. This is a mandatory property which cannot be removed.

I agree in cutting dc:description and removed it from the latest revision of the specification (rev 1.5)
