### ISSUE TITLE
missing bibo namespace ?

### ISSUE THREAD

**Issue by chrmor** [DM2E/dm2e-mappings#15]
Example:
http://data.dm2e.eu/data/html/resourcemap/bbaw/dta/16168_f0004/1391002599515

in this RDF the URL http://purl.org/ontology/bibonumber seems wrong.
I guess the correct one is http://purl.org/ontology/bibo/number

**Comment by ksdm2e** [comment]
I fixed that already in my xslt in january. Should be ingested again.
