### ISSUE TITLE
Untyped literal in dcterms:created

### ISSUE THREAD

**Issue by ksdm2e** [DM2E/dm2e-mappings#17]
dm2e-validation.jar NOTICEs: 

<pre>
has untyped literal for property <http://purl.org/dc/terms/created>.
</pre>

The values in the file are **2014-01-09T23:16:06Z**, which are valid _xsd:dateTime_.

DM2E-spec lists _edm:TimeSpan_, _xsd:dateTime_, _rdf:Literal_ as possible ranges for dcterms.

Why is it NOTICEd? Or what is a better notation?

**Comment by d0rg0ld** [comment]
did you use rdf:datatype="http://www.w3.org/2001/XMLSchema#dateTime" as attribute? I am currently updating the Recommendations accordingly - Sorry for the inconvenience.

**Comment by ksdm2e** [comment]
Thanks!
