### ISSUE TITLE
has specific Problem: Aggregation contains both edm:isShownAt and edm:isShownBy.

### ISSUE THREAD

**Issue by ksdm2e** [DM2E/dm2e-mappings#18]
First: there are no problems, there are only challenges!

What does it mean? 

In the case of dta, edm:isShownAt, edm:isShownBy and edm:object point to different resources, according to the spec. 

If there is a problem, the spec is too complex.

**Comment by d0rg0ld** [comment]
I second to that. It should be possible, because the two different properties have different semantics.

**Comment by kba** [comment]
It's a NOTICE, the "Specific problem" is just a catch-all phrase for miscellaneous things that the validator notices which aren't necessary problems.

You can set the minimum level to WARNING to see only actual problems (Run with `--level WARNING`).

**Comment by ksdm2e** [comment]
I only use ERROR :smile:

**Comment by ksdm2e** [comment]
But anyway: if it's not a problem, why is it noticed?

**Comment by kba** [comment]
> I only use ERROR 

I can' reproduce this. For me, it shows as a NOTICE and is hidden when the level option is raised. Please provide input data and describe how you used the tool. Independent of whether this NOTICE should be raised at all, it should not appear in the results when you set the level.

**Comment by ksdm2e** [comment]
oh, sorry for the confusion. of course it's a NOTICE, but as far as the message "has specific Problem:" is missleading or not important to be valid, I've choosen ERRORS only.

But again: Why is it a notice? And what's the problem with it?

**Comment by kba** [comment]
Removed it, I was just wondering why you got the NOTICE even though you set the level.
