### ISSUE TITLE
BLOCKING: No dc:format for the AnnotatableVersion

### ISSUE THREAD

**Issue by chrmor** [DM2E/dm2e-mappings#19]
Example:

http://data.dm2e.eu/data/rdf/resourcemap/mpiwg/harriot/MPIWG_01QU84RT_00817/1393267718023

there is not triple specifying the format.

What should the format be? text/html?

**Comment by kba** [comment]
The link in `dm2e:hasAnnotatableVersionAt` (http://thrax.mpiwg-berlin.mpg.de/mpiwg-mpdl-cms-web/query/GetPage?docId=/echo/en/Harriot_Add_MS_6789_0VGM2B80.xml&page=817) points to a page containing 

```
[???] 
[ways] 
[basn] 
```

@kthth @jurzua Is this art or have you been hacked or something? :D

**Comment by kba** [comment]
Ah, I guess it's just an empty page.

**Comment by kba** [comment]
This error will lead to a FATAL validation error which prevents ingestion of such data.

**Comment by kba** [comment]
Pages in harriott do now have dc:format for all WebResources, e.g. http://data.dm2e.eu/data/rdf/resourcemap/mpiwg/harriot/MPIWG_01QU84RT_00705/20140304151523204?output=ttl
