### ISSUE TITLE
ShownAt links broken?

### ISSUE THREAD

**Issue by chrmor** [DM2E/dm2e-mappings#20]
The shownAt link seems broken as it lands on a [Empty Page], while the AnnotatableVersion does contain text.

See for example this one:

http://data.dm2e.eu/data/html/resourcemap/mpiwg/harriot/MPIWG_01QU84RT_00793/1393267718023

**Comment by kthth** [comment]
Yes, working on it.

**Comment by chrmor** [comment]
Is this one fixed?
Can you point me at something that is not an Empty Page ?

**Comment by kthth** [comment]
is fixed, you find good examples around page http://data.dm2e.eu/data/html/resourcemap/mpiwg/harriot/MPIWG_5PYT50NY_00075/20140306175430512
Most verso pages are blank.
