### ISSUE TITLE
Why do crm:P79F.beginning_is_qualified_by and crm:P80F.end_is_qualified_by have xsd:dateTime as range?

### ISSUE THREAD

**Issue by d0rg0ld** [DM2E/dm2e-mappings#22]

**Comment by kba** [comment]
Should they only contain a textual qualification of the `edm:begin`/`edm:end` value?

**Comment by d0rg0ld** [comment]
They were proposed to be used to describe the cause for uncertain data, according to the current recommendations, there are only two values allowed here:

"uncertainty_data" and "uncertainty_granularity"

**Comment by kba** [comment]
Fixed in the model version "1.1_Rev1.4" in the Validator. Please update.

**Comment by edroege** [comment]
Fixed in the model specifiaction (now in the next revision: 1.5)
