### ISSUE TITLE
BLOCKING: Missing Aggregation-to-Item connection

### ISSUE THREAD

**Issue by chrmor** [DM2E/dm2e-mappings#23]
Example:

http://data.dm2e.eu/data/rdf/resourcemap/mpiwg/harriot/MPIWG_KECMZ5BH_00003/1393267718023

In this RDF I see no aggregatedCHO property connecting the Item (CHO) with the Aggregation. This is mandatory!

**Comment by kba** [comment]
This error will lead to a FATAL validation error which prevents ingestion of such data.

**Comment by kba** [comment]
This was fixed by @kthth and reingested, see http://data.dm2e.eu/data/html/resourcemap/mpiwg/harriot/MPIWG_KECMZ5BH/20140304151523204.

Since this cannot happen anymore (the validator cancels the ingestion in this case), I'll close this.
