### ISSUE TITLE
subject must be repeatable

### ISSUE THREAD

**Issue by ksdm2e** [DM2E/dm2e-mappings#24]
Is there any reason, why a dc:subject is not repeatable?

Please correct that in the specs and validation tool. I can see no advantage in this decision.

**Comment by d0rg0ld** [comment]
Already changed in Rev 1.4 !

**Comment by kba** [comment]
Yes, is also fixed in the validator tool since yesterday.

**Comment by ksdm2e** [comment]
So is the a param for rev1.4? The help message needs an update.

**Comment by kba** [comment]
Please update, I rebuild the tool whenever I change the code base. The help message shows all available versions, so it is always in sync with the code.

**Comment by ksdm2e** [comment]
The version of this morning has no 1.4. I update from the same url?

**Comment by kba** [comment]
Yes.

**Comment by ksdm2e** [comment]
Thanks. I tried it already.

Who killed the owl:sameAs again?

Over and out ...

**Comment by kba** [comment]
If that last part was a problem description, please rephrase.

**Comment by ksdm2e** [comment]
There are no problems, there are only issues:

https://github.com/DM2E/dm2e-mappings/issues/26
