### ISSUE TITLE
 Rev1.4: has unknown property owl#sameAs

### ISSUE THREAD

**Issue by ksdm2e** [DM2E/dm2e-mappings#26]
When I check my data with the latest validation-tool with _-version 1.1_Rev1.4_, the following error appears:

http://data.dm2e.eu/data/agent/bbaw/authority_gnd/1018099549:
        [ERROR]  has unknown property http://www.w3.org/2002/07/owl#sameAs

But according the spec, it is _optional_ (p. 53)

Wrong namespace?

**Comment by kba** [comment]
Was fixed yesterday, please update.
