### ISSUE TITLE
[FATAL]  is missing required property <http://purl.org/dc/elements/1.1/format

### ISSUE THREAD

**Issue by ksdm2e** [DM2E/dm2e-mappings#27]
<pre>
[FATAL]  is missing required property <http://purl.org/dc/elements/1.1/format> (Condition: Annotatable WebResource)
</pre>

Not every WebResource is annotatable, e.g. the WebResource for a book points to a landing page. I am not sure, this validation is too strict.

I fixed it in my code anyway.

**Comment by ksdm2e** [comment]
Or may I say: 

Not every WebResource is worth to be marked as relevant for pundit from the perspective of the dataprovider.

**Comment by kba** [comment]
The validator differentiates between WebResources in general and Annotatable WebResources, i.e. those that are the object of triples with the properties:
- edm:isShownBy
- edm:isShownAt
- edm:object
- dm2e:hasAnnotatableVersion

Only WebResources used in this context must have the dc:format property set.

See p.45 of the current specs on `dc:format` in `edm:WebResource`:

```
mandatory (for
the annotatable
resources,
otherwise: )
```

**Comment by ksdm2e** [comment]
I omitted _dc:format_, where I do not expect the resource to be annotated. So the constraint doesn't fit here.

I use "text/html" now, but not “text/html-named-content”, so my WebResources are not marked as relevant for annotation (maybe; i have no feedback dta is suitable for pundit).

(Please: do not close issues to fast.)

**Comment by kba** [comment]
Okay, after discussion with @d0rg0ld  @edroege and @JIwanowa I'll change the validator to emit FATAL only when WebResources in `dm2e:hasAnnotatable` relations don't have dc:format.
