### ISSUE TITLE
[WARNING]  is missing strongly recommended foobar

### ISSUE THREAD

**Issue by ksdm2e** [DM2E/dm2e-mappings#28]
Please change [WARNING]s, which are based on recommendations, to [INFO].

That's much more friendly.

(Thanks @kba! Finished. And announce updates.)

**Comment by kba** [comment]
Currently, I have
- NOTICE (for things that are not a problem but may have eluded the mapper's attention)
- WARNING (for things that are not errors, but that contradict strong recommendations in the model)
- ERROR (for things that contradict strict assertions in the model, such as mandatory elements missing)
- FATAL (for errors that cripple the data to an extent where it can't be worked with sensibly)

So, I think a WARNING is justified if the recommendations aren't followed. It's not intended to be friendly or unfriendly to the validator, it's a warning of potential problems this may cause for consumers of the data.

**Comment by ksdm2e** [comment]
Let me connect the second point and your last sentence: If a missing recommendation is causing a problem, then it should be an obligation (in our terms _mandatory_). A consumer shouldn't rely on recommended properites at all. Never.

But, a recommendation is a proposal or a nice-to-have. It depends on the potential of the existing data.

In my case: I don't want to be WARNed because of a missing whatever. I know that there's no subject on this page, because usually a page has no such a thing like subject. What is this WARNING good for?

A "WARNING" has an other priority and meaning.

How about [RECOMMENDATION] instead?

**Comment by kba** [comment]
If the recommendations strongly recommend something, the validator will warn you when that recommendation is not fulfilled. This is the definition of WARNING (see https://github.com/DM2E/dm2e-ontologies/blob/master/src/main/java/eu/dm2e/validation/ValidationLevel.java?source=c). If that particular strong recommendation is too strong, please request to change the specs instead.

Besides, you can filter by ValidationProblemCategory (https://github.com/DM2E/dm2e-ontologies/blob/master/src/main/java/eu/dm2e/validation/ValidationProblemCategory.java) if you are not interested in fulfilling the recommendations. Just run the tool with the `--terse` option and skip all lines that contain `MISSING_RECOMMENDED_PROPERTY`.

**Comment by kba** [comment]
There hasn't been any feedback to the contrary, so I assume `WARNING` is okay for missing strongly recommended properties for the data mappers.

If not, please re-open.

**Comment by ksdm2e** [comment]
There is no need to hurry.

**Comment by edroege** [comment]
Looks good to me @kba !

**Comment by kba** [comment]
@ksdm2e Why can't this be closed?

**Comment by kba** [comment]
@ksdm2e Why can't this be closed?

**Comment by kba** [comment]
If you have new points, please re-open.

**Comment by ksdm2e** [comment]
Wait ...

**Comment by kba** [comment]
Please stop re-opening this if you have no new arguments. This is annoying.
