### ISSUE TITLE
Proposal: Make dc:format mandatory for WebResources referenced by edm:object

### ISSUE THREAD

**Issue by kba** [DM2E/dm2e-mappings#29]
According to the EDM v.5.2.4 (http://pro.europeana.eu/documents/900548/0d0f6ec3-1905-4c4f-96c8-1d817c03123c) and the Europeana Portal Image Policy (http://pro.europeana.eu/documents/900548/960640/Europeana+Portal+Image+Policy), the WebResource referenced by `edm:object` in an `ore:Aggregation` should be:
- the URL to an image representation of the CHO in the highest resolution available on the provider's web site
- in an image format supported by the image processing library ImageMagick
- at least 200px wide

Since this is the property that both Europeana Portal and DM2E will use for display in the respective search interfaces, it would simplify the thumbnail generation process if we knew what MIME type such a WebResource has.

Therefore I propose to make `dc:format` **mandatory** for WebResources that are the related to an `ore:Aggregation` using the `edm:object` property.

The following MIME types should be supported:
- image/png
- image/jpeg
- image/gif
- image/tiff
- application/pdf 

PDF may only be used if the first page of the PDF is the representation of the CHO.

**Comment by d0rg0ld** [comment]
I would only make dc:format mandatory for edm:object - WebResources if you can _make sure_ that all possible source data formats understood by ImageMagick (As said in the Europeana Portal Image Policy) are allowed as MIME type. Otherwise (and most likely) I suggest not to make it mandatory

**Comment by kba** [comment]
Yes, that is what I meant: Only for WebResources that are used as objects related by `edm:object` to the Aggregation, **not** WebResources in general. Yes, the list of MIME types is probably not exhaustive, we can expand it when the need arises but I would like the validation to notice when something unusual is set, so I need a fixed set of values (i.e. prevent `text/html` and such).

**Comment by edroege** [comment]
Added as proposed by kba in rev 1.5
