### ISSUE TITLE
Books without pages and author

### ISSUE THREAD

**Issue by chrmor** [DM2E/dm2e-mappings#3]
http://141.20.126.232/data/html/resourcemap/onb/abo/%2BZ101315405/1391106413338
is this correct? : http://141.20.126.232/data/... shouldn't it be a domain name?
There is not author triple. Is it correct?
The rdf:type is Book but it does not contain pages. Is it correct? What should I annotate then?

**Comment by kba** [comment]
> shouldn't it be a domain name?

Pubby was configured to use the request Hostname as the hostname for the generated URIs. Hence when you request http://141.20.126.232/data/html/resourcemap/onb/abo/%2BZ101315405/1391106413338 you will get resources starting with http://141.20.126.233. 

Where did you find this link?

> There is not author triple. Is it correct?

I assume the edm:hasMet relation contains the author (someone known by the initials B.S.?)

**Comment by chrmor** [comment]
In order to show the author we need a clear property for the author. hasMet is generic and I cannot assume it points to the author ....

**Comment by kba** [comment]
Yes, there is `pro:author` for that, I think.

**Comment by d0rg0ld** [comment]
Hi there, the problem is that for ABO metadata I dont know the exact roles of persons. In most cases, it will be the author, but not necessarily. Therefore It would simply be incorrect to refer to all these persons as authors and thus hasMet is the only way to describe the relationship between persons and the item.

**Comment by d0rg0ld** [comment]
Regarding pages: As I wrote a couple of days ago, we currently only deliver data on item level for the ABO collection

**Comment by kba** [comment]
Cannot really be fixed for this particular case, but subclassing a few properties to dc:creator/dc:contributor (#111) will help in similar cases.
