### ISSUE TITLE
Is the dingler dataset empty?

### ISSUE THREAD

**Issue by chrmor** [DM2E/dm2e-mappings#30]
http://data.dm2e.eu/data/html/dataset/uber/dingler/1392199702509

**Comment by edroege** [comment]
Strange. Is this an ingestion error? @kba can you help?

**Comment by JIwanowa** [comment]
Hi Christian, this dataset is empty indeed. I ingested a new dataset today, which is only for test purposes. You can find this: http://data.dm2e.eu/data/html/dataset/uber/dingler/1393515961557  
The CHOs on Page-Level are here: http://data.dm2e.eu/data/html/resourcemap/uber/dingler/issue_pj001/1393515961557 and for the second issue here: http://data.dm2e.eu/data/html/resourcemap/uber/dingler/issue_pj022/1393515961557

The full dataset will be ingested asap. I am working on some bugs within the mapping.

**Comment by chrmor** [comment]
Please notify when you have a new dataset ingested. The test one is gone

**Comment by kba** [comment]
http://data.dm2e.eu/data/html/dataset/uber/dingler/1393515961557
