### ISSUE TITLE
Missign edm:object

### ISSUE THREAD

**Issue by chrmor** [DM2E/dm2e-mappings#31]
Example:
http://data.dm2e.eu/data/html/resourcemap/onb/abo/%2BZ103504606/1391106413338

there is no edm:object triple. This is needed to provide a preview of the book.
Isn't it mandatory in the mapping?

**Comment by d0rg0ld** [comment]
It is not mandatory and currently we are not able to provide edm:object (Although I hope that we will do so soon). At the Moment, only edm:isShownAt links will be provided with ABO content

**Comment by chrmor** [comment]
I really do not know what to show for this dataset. There is no content, images, texts, etc. I'll just skip it at the demo :-/

**Comment by d0rg0ld** [comment]
I think this will be the best thing to do

**Comment by kba** [comment]
This is a WONTFIX for abo, so I close this for now.
