### ISSUE TITLE
Dates are difficult to use

### ISSUE THREAD

**Issue by chrmor** [DM2E/dm2e-mappings#32]
Representing dates like resources is ok. 
Example:
http://data.dm2e.eu/data/timespan/onb/abo/1763-01-01T000000UG_1763-12-31T235959UG

But consuming this is very heavy as I need to get a full RDF resources with a lot of links that I do not need.
Would it be possible to include the date also as Literal in the RDF description of a e.g. persons?

**Comment by d0rg0ld** [comment]
Already a while ago we decided to represent dates this way, mostly because we had to normalize dates to a common format, which is xsd:dateTime here. Unfortunately this resulted in the necessity to represent dates that are eg given as YYYY only as uncertain timespans ranging from YYYY-01-01T00:00:00 to  YYYY-12-31T00:00:00 . 

So right now you will find two different versions of dates:
literals of rdf:datatype "xsd:dateTime" or edm:TimeSpans 

 For now, I fear, you will have to stick with this representation...

**Comment by d0rg0ld** [comment]
TimeSpans, however will have a label that you can find with the skos:prefLabel property of the timespan resource

**Comment by kba** [comment]
In the Linked Data API Java Client, I use this method for parsing dates:

``` java
    public DateTime getDateTimeForProp(final Resource theResource, final String theProp) {
        Statement stmt = theResource.getProperty(getModel().createProperty(theProp));
        if (null == stmt)
            return null;

        RDFNode obj = stmt.getObject();
        String toParse = null;
        if (obj.isLiteral()) {
            toParse = obj.asLiteral().getLexicalForm();
        } else if (obj.isURIResource()) {
            try {
                getModel().read(obj.asResource().getURI());
                Statement beginStmt = obj.asResource().getProperty(getModel().createProperty(NS.EDM.PROP_BEGIN));
                if (null != beginStmt && beginStmt.getObject().isLiteral()) {
                    toParse = beginStmt.getObject().asLiteral().getLexicalForm();
                }
            } catch (Exception e) {
                log.error("Error reading " + obj.asResource());
            }
        }
        DateTime ret = null;
        try {
            ret = DateTime.parse(toParse);
        } catch (Exception e) {
            log.debug("Error parsing date '{}'", toParse);
        }
        return ret;
    }
```

If the date is a literal, try to parse it as an xsd:dateTime. If it is a resource, assume it to be an edm:TimeSpan and parse the edm:begin of it as an xsd:dateTime. While rather simplistic, using this approach covers those cases where you can get a reasonable result for processing further (i.e. a known dates and years which is the most common case).

But as you said, you need to dereference the date resource to get the date, there is no way around that at the moment.

@kaiec Maybe we could include edm:TimeSpan in the ResourceMap?

**Comment by kba** [comment]
edm:TimeSpans are now included in the resourceMap. For example http://data.dm2e.eu/data/rdf/resourcemap/onb/codices/%2BZ103904402/20140304184952678?output=ttl contains the referenced timespans, no need to dereference them in a second HTTP request.

Please reopen if this doesn't fix the issue for you.
