### ISSUE TITLE
Remove fabio:Page

### ISSUE THREAD

**Issue by chrmor** [DM2E/dm2e-mappings#34]
Example: 
http://data.dm2e.eu/data/html/resourcemap/uib-ffm/sammlungen/urn:nbn:de:hebis:30:2-11683-phys1970999/1390576653139

http://purl.org/spar/fabio/#Page is wrong, you should use dm2e:Page!

**Comment by knepper** [comment]
Strange dataset (wrong provider name with an extra i) is - apart from this - months old and completely obsolete. See ticket #5. All data http://data.dm2e.eu/data/html/resourcemap/uib-ffm/sammlungen need to deleted but I cannot. Causes continuous confusion.

Please note the wrong privider name "uib-ffm" with an extra i.

**Comment by knepper** [comment]
This obsolete dataset is deleted now, thanks - Solved!
