### ISSUE TITLE
Single pages without book?

### ISSUE THREAD

**Issue by chrmor** [DM2E/dm2e-mappings#35]
CHOs are single pages? No CHO (boo)k exists that contains them.
It is correct?
How should I treat them?

**Comment by knepper** [comment]
No. There is always a book that contains the pages. Can you give me hint to track this issue, just an example of a single page?
From the numbers of the ingested titels and pages I can see that there is a significant loss of data ( ca. 20%) after ingestion. If the book is lost and the pages are not - this might be the result.

How can this loss happen?

However, if I have an identifier I can check my data to make sure that there is book containing the pages.

**Comment by kba** [comment]
@knepper You're right, there was a loss of data at ingestion, we're still hunting down the cause of the problem. Could well be that this is the source of the problem. @chrmor please provide an example URL so we can investigate.

**Comment by chrmor** [comment]
the dataset is empty at the moment...waiting for re-up and the Ill check

**Comment by knepper** [comment]
They are in the queue since yesterday and I hope they are ingested soon.

**Comment by kba** [comment]
Was re-ingested completely tonight.

**Comment by knepper** [comment]
Ingest is there! Look at this example:

http://data.dm2e.eu/data/html/resourcemap/ub-ffm/sammlungen/291036384/20140301004538912

Do you still find pages without book? If so, please send a link/id.

**Comment by knepper** [comment]
Is the problem with ingest losses solved? Did you check the number of ingested items?

**Comment by kba** [comment]
i have no numbers, but this ingest sent through without problems, no losses.

**Comment by knepper** [comment]
Nice :-)
