### ISSUE TITLE
Cannot understand the correct version to check!

### ISSUE THREAD

**Issue by chrmor** [DM2E/dm2e-mappings#36]
I cannot get what is the correct version of the dataset, some are empty some have messy data.

Please delete the old datasets if possible! Or clearly give a name to the version last version.

**Comment by chrmor** [comment]
I guess the correct version is 
http://data.dm2e.eu/data/html/dataset/ub-ffm/sammlungen/1393382287795

How do I recognize it when the url will change?

**Comment by knepper** [comment]
I have the same problem. I have problems to find my data and my versions. The more I work on my data the bigger gets the mess of versions.

This cited version is quit new and should be not too bad.

**Comment by kba** [comment]
http://data.dm2e.eu/data/html/dataset/ub-ffm/sammlungen/1393382287795 is the version I ingested last night. The newer versions were generated while we've been hunting down the bug that made the ingestion croak on Marko's (valid) data.

**Comment by knepper** [comment]
The old versions are deleted, I can already see ingestion tests for the new data, thanks again - solved!
