### ISSUE TITLE
Gei Digital is Empty!

### ISSUE THREAD

**Issue by chrmor** [DM2E/dm2e-mappings#37]
http://data.dm2e.eu/data/html/dataset/gei/gei-digital/1391717717253

.. or I'm looking at the wrong version? please delete old versions!

**Comment by knepper** [comment]
gei-digital needs the last model adaptions (rdf:datatpye...) - can be deleted completely. New dataset is coming soon.

Check ub-ffm first.

**Comment by chrmor** [comment]
Please notify when you have a new dataset ingested.

**Comment by kba** [comment]
Ingestion is running currently, about 70% done. Give it another hour or so and it should be finished. When it is, result will be at http://data.dm2e.eu/data/dataset/gei/gei-digital/20140228141018901

**Comment by knepper** [comment]
Ingest is done, but the link is
http://data.dm2e.eu/data/dataset/gei/gei-digital/20140301021526607

An example book is
http://data.dm2e.eu/data/html/resourcemap/gei/gei-digital/PPN638179718/20140301021526607
It is a book with pages which is part of a multivolume book. (The multivolume book has no pages but the volumes.)
