### ISSUE TITLE
bibo:Issue is missing in the DM2E Model Specs as allowed PhysicalThing subtype

### ISSUE THREAD

**Issue by kba** [DM2E/dm2e-mappings#39]
In "3.7 edm:PhysicalThing: Subclasses" there is no Class defined for an Issue of a serial work. This should be `bibo:issue` I think.

**Comment by JIwanowa** [comment]
Yes, we already use bibo:Issue in the UBER mapping. We'll add the bibo:Issue as Subclass of edm:PhysicalThing in the DM2E specification Rev1.5.

**Comment by kba** [comment]
Fixed in 1.1_Rev1.5-DRAFT of the validator.

**Comment by edroege** [comment]
Added in model rev 1.5
