### ISSUE TITLE
Empty datasets

### ISSUE THREAD

**Issue by chrmor** [DM2E/dm2e-mappings#4]
http://data.dm2e.eu/data/html/dataset/onb/codi/1391095292351, http://data.dm2e.eu/data/html/dataset/onb/codices/1391337499559, 
this seems empty

**Comment by d0rg0ld** [comment]
Data needs some update, will do this week. Best, Doron

**Comment by chrmor** [comment]
Any update on this dataset?

**Comment by d0rg0ld** [comment]
Working on it _today_, only minor changes. I hope to be finished in the evening and will let you know.

**Comment by d0rg0ld** [comment]
Finished with the Codices mapping, sent data as tar to @kba and @Dommii for ingestion. OmNom seems to be down right now (Josso Login not available)

**Comment by kba** [comment]
@d0rg0ld Omnom is up and running: http://omnom.dm2e.eu.

Ingestions are running.
