### ISSUE TITLE
Error when running validator

### ISSUE THREAD

**Issue by d0rg0ld** [DM2E/dm2e-mappings#41]
I am trying to run 

java -jar dm2e-validate.jar -version "1.1_Rev1.4" -terse test.rdf

on a file successfully validated in http://www.w3.org/RDF/Validator/rdfval

and I only get the following error message:

! Jena croaked on file /media/sf_devel/test.rdf. Are you sure it is 'RDF/XML'.  http://RELATIVE_URL/ Code: 11/LOWERCASE_PREFERRED in HOST: lowercase is preferred in this component

Please find the content of the file here http://wiki.dm2e.eu/wiki/images/5/51/Validate_Test.zip

**Comment by d0rg0ld** [comment]
btw, it is the newest (27.2. 18:00) version of the jar file

**Comment by kba** [comment]
Should be fixed now, please update.

**Comment by d0rg0ld** [comment]
Great, works now. So far it looks good, I just get one annoying error:

[ERROR] INVALID_DATA_PROPERTY_RANGE     http://purl.org/ontology/bibo/number

bibo number is set to http://www.w3.org/2001/XMLSchema#unsignedInt - is it not implemented yet? What else should I use?

Thanks!

**Comment by kba** [comment]
1.1_Rev1.3 and 1.1._Rev1.4 expect `xsd:int`. I included a draft of the next revision 1.1_Rev1.5 which expects `xsd:unsignedInt`.

Edit: Ah, I actually forgot to expose that in the tool, will fix right away.

**Comment by d0rg0ld** [comment]
ok thanks, I will stick to 1.4 now ...

**Comment by d0rg0ld** [comment]
!! Error parsing command line options:  Unrecognized version string '1.1_Rev1.5-DRAFT'

**Comment by kba** [comment]
Sorry, still building :)

**Comment by kba** [comment]
Ok, now it's finished, please re-download.

**Comment by d0rg0ld** [comment]
thx, seems to work now, I validate the files and will report then ...

**Comment by kba** [comment]
all right, keep in mind, that 1.5 is a DRAFT, I will make sure that the behavior is correct when the new version is released.

**Comment by d0rg0ld** [comment]
[ERROR] UNKNOWN_PROPERTY  http://rdvocab.info/ElementsGr2/otherDesignationAssociatedWithTheCorporateBody

This property is already part of Rev1.3

**Comment by kba** [comment]
Will fix but please open a new issue next time https://github.com/DM2E/dm2e-mappings/issues/42

**Comment by d0rg0ld** [comment]
ok, i will!
