### ISSUE TITLE
Unofficial namespace?

### ISSUE THREAD

**Issue by chrmor** [DM2E/dm2e-mappings#44]
The data at:
http://data.dm2e.eu/data/html/dataset/ub-ffm/sammlungen

is using now an "UNOFFICIAL" namespace.
Also datasets are empty.

**Comment by kba** [comment]
No, the UNOFFICIAL namespace (http://onto.dm2e.eu/UNOFFICIAL/) is being used for things related to pubby/linked data api. They should be moved into the official dm2e ontology ASAP.

**Comment by knepper** [comment]
Who should move? Where are my data? Help :-)

This is the data file (fra-item-DM2Ev11Rev14-2014-02-27-rdf.zip):
http://omnom.dm2e.eu/api/file/1c8e2557-854b-4213-8c6d-9f264be7a1e5

**Comment by kba** [comment]
This has nothing to do with data providers, it just concerns a few (five or so) properties that we use in Pubby. 

Your data will be ingested tonight and be available at http://data.dm2e.eu/data/dataset/ub-ffm/sammlungen/20140301004538912.

**Comment by kba** [comment]
Is ingested.

**Comment by knepper** [comment]
Ingested data look nice - thanks!

But what does it mean: "They should be moved into the official dm2e ontology ASAP."

**Comment by kba** [comment]
The UNOFFICIAL namespace issue is largely fixed, for the remaining properties, see #63
