### ISSUE TITLE
Difficult to handle content for Annotation

### ISSUE THREAD

**Issue by chrmor** [DM2E/dm2e-mappings#47]
Resource like the following

http://data.dm2e.eu/data/html/resourcemap/uber/dingler/page_pj022_pb150/1393515961557

have an Annotatable Version that is an HTML page.
Is contains both text (trascription) and images (facsimile).
It would be VERY IMPORTANT to SHOW THEM IN THE DEMO.

However:
Images are enclosed in a viewer and text is somewhere in the HTML DOM.
Does this respect the specifications we agreed? I would like to have links to Images and texts, if possible separately. so I can aggregate them in Feed and annotate them.

Question: what is the why of connecting a transcription to its facsimile? Is the model supporting this?

**Comment by JIwanowa** [comment]
Sorry, but we have to map facsimiles-images and transcription-html into the same CHO. The reason for that is, that we have no possibility to extract neither the images nor the transcriptions. The resources will be of the type like this: http://dingler.culture.hu-berlin.de/journal/page/pj001?p=00000017

As we are not the owner of the resources and don't have any access to the backend database, we can not set up a service to save the images in a separate html page. The same thing is regarding the transcriptions.

The only possible approach would be to include the images also as single page like this: http://www.polytechnischesjournal.de/fileadmin/data/32258227Z/32258227Z_tif/jpegs/00000017.tif.medium.jpg  

But these aren't simple HTML pages with standard <img> tag too. Therefore we decided to take the mixed pages into the mappings. We made some tests with pundit as well and there were no significant differences in the annotation functions. Furthermore we think it would be better for the user to have both facsimiles and images parallel on the screen.

I hope you can still deal with the mixed resources.

**Comment by chrmor** [comment]
Ok I'll try to support this in some way.
In the meantime...where is the dataset? :-)
