### ISSUE TITLE
Different kind of Pages...

### ISSUE THREAD

**Issue by chrmor** [DM2E/dm2e-mappings#5]
http://data.dm2e.eu/data/html/dataset/uib-ffm/sammlungen/1390576653139
here the contained CHOs are Pages, there is no Book level: http://data.dm2e.eu/data/html/resourcemap/uib-ffm/sammlungen/urn:nbn:de:hebis:30:2-11683-phys1970992/1390576653139
Note that the rdf:type used is http://purl.org/spar/fabio/#Page and not dm2e:1.0/Page as in other datasets.

**Comment by JIwanowa** [comment]
The fabio:Page is wrong, the right URI for the rdf:type is now http://onto.dm2e.eu/schemas/dm2e/Page

**Comment by knepper** [comment]
This is a strange test data set ("uib-ffm" instead of "ub-ffm"), please delete everything with "uib-ffm".
The data are months old (before Athens) and follow an old model. Correct is "ub-ffm".

**Comment by knepper** [comment]
Obsolete dataset.
