### ISSUE TITLE
dc:format problem

### ISSUE THREAD

**Issue by chrmor** [DM2E/dm2e-mappings#51]
dc:format should be associated to the AnnotatableVersion an not to the aggregation, as in:

http://data.dm2e.eu/data/rdf/resourcemap/mpiwg/harriot/MPIWG_D69UV91B_00009/20140228232845114

**Comment by kba** [comment]
Ah, this is a weird SPARQL query in Pubby:

```
conf:sparqlQuery '''CONSTRUCT {
    ?s ?p ?o .
    ?av <http://purl.org/dc/elements/1.1/format> ?format .
tp://example.org/resourcemap> .
} WHERE {
    graph <http://data.dm2e.eu/data/dataset/$1/$2/$4> {
        ?s ?p ?o .
        OPTIONAL {
            ?s <http://onto.dm2e.eu/schemas/dm2e/1.1/hasAnnotatableVersionAt> ?av. ?av <http://purl.org/dc/elements/1.1/format> ?format
        }
    }
    FILTER (
        ?s = <http://data.dm2e.eu/data/item/$1/$2/$3> ||  ?o = <http://data.dm2e.eu/data/item/$1/$2/$3>
     || ?s = <http://data.dm2e.eu/data/aggregation/$1/$2/$3> ||  ?o = <http://data.dm2e.eu/data/aggregation/$1/$2/$3>
   )
} ''';
```

@kaiec you know why this is?

Can't fix right now though, because ingestions are running.

**Comment by d0rg0ld** [comment]
I think that two things are mixed up here. If I retrieve the RDF for my codices example - http://data.dm2e.eu/data/rdf/resourcemap/onb/codices/%2BZ103938400_101/20140301001753486 - dcformat is _NOT_ in the aggregation. Therefore we are dealing with two distinct problems here, IMHO

**Comment by kba** [comment]
OK, there's an error in the data anyway (that dc:format is assigned to the aggregation) but the SPARQL error should be fixed now.

**Comment by d0rg0ld** [comment]
Looks good, thanks!

**Comment by kaiec** [comment]
Sure, this adds the tripel about the format of the annotatable version
to the RDF data for Christian.

Am 03.03.2014 21:32, schrieb kba:

**Comment by kaiec** [comment]
Ah, now I see it. Of course the 1.1 in the URI has to be removed to get
it working again. @kba: Do you fix this?

Am 04.03.2014 10:58, schrieb Kai Eckert:

**Comment by kba** [comment]
No, the old SPARQL assigned the dc:format of all annotatable web resources to the aggregation which was wrong. Now I just add all the annotatable web resources as a whole to the resourcemap:

```
conf:sparqlQuery '''CONSTRUCT {
    ?s ?p ?o .
    ?as ?ap ?ao .
    ?s a <http://example.org/resourcemap> .
} WHERE {
    GRAPH <http://data.dm2e.eu/data/dataset/$1/$2/$4> {
        ?s ?p ?o .
        OPTIONAL {
            ?s <http://onto.dm2e.eu/schemas/dm2e/hasAnnotatableVersionAt> ?as.
            ?as ?ap ?ao.
       }
    }
    FILTER (
        ?s = <http://data.dm2e.eu/data/item/$1/$2/$3> ||  ?o = <http://data.dm2e.eu/data/item/$1/$2/$3>
     || ?s = <http://data.dm2e.eu/data/aggregation/$1/$2/$3> ||  ?o = <http://data.dm2e.eu/data/aggregation/$1/$2/$3>
   )
} '''; 
```
