### ISSUE TITLE
No pages on this one?

### ISSUE THREAD

**Issue by chrmor** [DM2E/dm2e-mappings#53]
http://data.dm2e.eu/data/item/ub-ffm/sammlungen/322980143

**Comment by knepper** [comment]
No. Pages are lost at mapping time, will be fixed.

**Comment by kba** [comment]
Shall I put a rule into the validator that NOTICEs Manuscripts, Books, Articles without Pages?

**Comment by edroege** [comment]
@kba good idea

**Comment by knepper** [comment]
@kba A NOTICe is nice - although there might always be multivolume records without pages.

Fixed now in mapping version 10 and in all datasets from today and later.
