### ISSUE TITLE
Authors resources not reachable

### ISSUE THREAD

**Issue by chrmor** [DM2E/dm2e-mappings#56]
From here:

http://data.dm2e.eu/data/html/resourcemap/onb/codices/%2BZ103990409/20140301001753486

I cannot access the author resource:
http://data.dm2e.eu/data/agent/onb/codices/%2BZ103990409%2FVerschiedene_%5BVerfasser%5D

**Comment by d0rg0ld** [comment]
I think I have to fix the URI

**Comment by kba** [comment]
I think this is an issue with Pubby, the request is not even passed on to Fuseki.

**Comment by d0rg0ld** [comment]
but why does it work for other resources? http://data.dm2e.eu/data/html/agent/onb/authority_gnd/138907285 works. Probably its due to the special chars in the URI?

**Comment by kba** [comment]
Yes, the last URL segments encodes

```
+Z103990409/Verschiedene_[Verfasser]
```

So yes, the Slash is the problem I suppose.

**Comment by d0rg0ld** [comment]
Ok, Ill try to fix it - Will have to reingest later today

**Comment by kba** [comment]
This was fixed by latest ingest, http://data.dm2e.eu/data/html/dataset/onb/codices/20140304184952678. See for example http://data.dm2e.eu/data/html/resourcemap/onb/codices/%2BZ103904402/20140304184952678, contains `pro:author` http://data.dm2e.eu/data/html/agent/onb/codices/%2BZ103904402/Unbekannt
