### ISSUE TITLE
missing format for the annotatable object

### ISSUE THREAD

**Issue by chrmor** [DM2E/dm2e-mappings#6]
http://data.dm2e.eu/data/rdf/resourcemap/uib-ffm/sammlungen/urn:nbn:de:hebis:30:2-11683-phys1971057/1390576653139
there is no dc:format scpecified for the Annotatable object!

**Comment by knepper** [comment]
Strange and very old test data "uib-ffm". Please delete everything with "uib-ffm". Continous confusion...

**Comment by chrmor** [comment]
So the dataset http://data.dm2e.eu/data/dataset/uib-ffm/sammlungen is invalid?

**Comment by kba** [comment]
Yes, as are many others. We'll re-ingest the store ASAP.

**Comment by knepper** [comment]
Yes. It is a a test ingest with very old data.

The proper path to our data is:
http://data.dm2e.eu/data/html/dataset/ub-ffm/sammlungen

But the current mapping seems to be not ingested yet. The files are:
fra6-item-DM2Ev11Rev13-2014-02-12-rdf.zip (634 Medieval Manuscripts)
fra3a-item-DM2Ev11Rev13-2014-02-12-rdf.zip (377 Hebrew Manuscripts)
I have uploaded them on 2014-02-12 to OMNOM which is offline now. Shall I send them somewhere else?

**Comment by chrmor** [comment]
Could you please send a mail or something when the store is re-ingested?

**Comment by kba** [comment]
@knepper Omnom is up and running but it's finally where it should be, at http://omnom.dm2e.eu. We have the data on the server and will ingest it ASAP.

@chrmor Yes, we will.

**Comment by knepper** [comment]
P.S:
The ProvidedCHOs of the current mapping can be identified by
http://onto.dm2e.eu/schemas/dm2e/#Manuscript
instead of
http://onto.dm2e.eu/schemas/dm2e/1.1/#Manuscript

**Comment by kba** [comment]
These URIs should be

http://onto.dm2e.eu/schemas/dm2e/Manuscript

and 

http://onto.dm2e.eu/schemas/dm2e/1.1/Manuscript

The fragment identifier is just an artifact by the ontology browser at onto.dm2e.eu. We exclusively use slash-URIs.
