### ISSUE TITLE
1.5-DRAFT issues in validator

### ISSUE THREAD

**Issue by d0rg0ld** [DM2E/dm2e-mappings#60]
1) should be fixed since Rev1.3 -> Probably still missing in the owl file

[ERROR] UNKNOWN_PROPERTY        http://rdvocab.info/ElementsGr2/otherDesignationAssociatedWithTheCorporateBody

2) [ERROR] ILLEGALLY_UNTYPED_LITERAL       http://purl.org/ontology/bibo/numPages
It is allowed to use rdf:Literal, so it does not have to be typed, is this correct?

**Comment by d0rg0ld** [comment]
@edroege could you please check if http://rdvocab.info/ElementsGr2/otherDesignationAssociatedWithTheCorporateBody is present in the current OWL file? Thanks a lot!

**Comment by kba** [comment]
2) fixed

1) fixed by hardcoding. dont have time to investigate further.

will push and publish when i have stable connection

**Comment by d0rg0ld** [comment]
thx!

**Comment by kba** [comment]
fixed and released as of build 'Tue Mar  4 17:47:46 CET 2014'. Please re-download

**Comment by d0rg0ld** [comment]
thx

**Comment by kba** [comment]
Correction, as of build 'Tue Mar  4 17:56:14 CET 2014'

**Comment by edroege** [comment]
@d0rg0ld This was not in the owl file. Fixed it and will replace the owl file on github and redmine. Thanks for noticing!
