### ISSUE TITLE
[FATAL] has unsupported MIME type 'text/html'

### ISSUE THREAD

**Issue by JIwanowa** [DM2E/dm2e-mappings#61]
Couldn't ingest more data due to an "[FATAL] has unsupported MIME type 'text/html'" Error. The text/html should be support at least for our data.

**Comment by kba** [comment]
text/html is allowed for dm2e:hasannotatableVersion webresources but not for edm:object webresources.

_please_ always provide input data, build date of the validator and how you used it and log output.

**Comment by JIwanowa** [comment]
thx! will be fixed into the next ingestion.
