### ISSUE TITLE
printedAt / publishedAt should be repeatable

### ISSUE THREAD

**Issue by d0rg0ld** [DM2E/dm2e-mappings#62]
@edroege / @JIwanowa / @kba : 

According to the MAB specification, the location of printing and publishing can be repeatable:

410 Ort(e) des 1. Verlegers, Druckers usw. 
410_ 
410a Verlagsort(e) 
Druckort(e) 
412 Name des 1.Verlegers, Druckers usw. 
412_ 
412a Verleger 
Drucker 
415 Ort(e) des 2. Verlegers, Druckers usw. 
415_ 
415a Verlagsort(e) 
Druckort(e) 
417 Name des 2.Verlegers, Druckers usw. 
417_ 
417a Verleger 
Drucker 

Actually there is already a contradiction in the model spec, because publisher / printer can be repeatable, but not publishedAt/printedAt

Therefore I kindly ask for making both properties repeatable, probably even in Rev 1.5

thx!

**Comment by ksdm2e** [comment]
And could you add a writtenAt?

**Comment by kba** [comment]
Is part of the validator /OWL version 1.1_Rev1.6

**Comment by edroege** [comment]
Made dm2e:publishedAt and dm2e:printedAt repeatable in rev 1.6

@ksdm2e Will add dm2e:writtenAt. Please give me a definition (dm2e:scopeNote) and probably restrictions for the property. I set the range to edm:Place as for dm2e:printedAt.

**Comment by ksdm2e** [comment]
eeh, pffh:

Indicates the place where the CHO was written.

If you like, you can restrict it to CHO classes, or dc:format respectively, which are usually handmade, like letters, manuscripts asf.

**Comment by edroege** [comment]
Thanks!
