### ISSUE TITLE
Unresolvable places in Harriott

### ISSUE THREAD

**Issue by kba** [DM2E/dm2e-mappings#66]
In http://data.dm2e.eu/data/html/resourcemap/mpiwg/harriot/MPIWG_0HE26A22/20140304151523204
is a place (could also be a WebResource but from the context I guess it's a edm:Place) http://data.dm2e.eu/data/place/mpiwg/harriot/MPIWG_0HE26A22/XVsH21V_Petworth%2C+UK

I cannot dereference this, nor is it in the ResourceMap, so the data is either not there at all (i.e. forgotten to include it at mapping time) or the triplestore chokes on the URL-encoded sequence '%2B+', i.e. ', ' (comma-space).

Please fix this, I assume all contextual references within the http://data.dm2e.eu/data namespace to be resolvable and be it a trivial is-a statement.

**Comment by kba** [comment]
In fact: Not just a trivial is-a statement but a skos:prefLabel is mandatory as well and I rely on that.

**Comment by kthth** [comment]
fixed by not replacing spaces with + but with underscore

**Comment by kba** [comment]
And cannot happen anymore because the validator throws FATAL errors for such URLs: https://github.com/DM2E/dm2e-ontologies/commit/633f3199d4309a42d080404b61afb766266675d9
