### ISSUE TITLE
com.hp.hpl.jena.query.QueryParseException: Encountered 

### ISSUE THREAD

**Issue by JIwanowa** [DM2E/dm2e-mappings#68]
Last ingestion: dm2e-ingest -c /data/INBOX/uber-dingler/julia-uber-dingler.properties
log: data/INBOX/uber-dingler/ingestion-uber-dingler-20140305114203921.log

ERROR
03/05 11:42:35: ===============================
03/05 11:42:35: Date: Wed Mar 05 11:42:35 CET 2014
03/05 11:42:35: File: /tmp/unzip_4683792936525352686/SubsetJournalRDF/ar107mi05.orig.xml
03/05 11:42:35: Output validated. Yay :)
03/05 11:42:35: Encountered " "<" "< "" at line 193, column 1.
Was expecting:
    "}" ...
    com.hp.hpl.jena.query.QueryParseException: Encountered " "<" "< "" at line 193, column 1.
Was expecting:
    "}" ...

```
    at com.hp.hpl.jena.sparql.lang.ParserARQUpdate._parse(ParserARQUpdate.java:67)
    at com.hp.hpl.jena.sparql.lang.ParserARQUpdate.parse$(ParserARQUpdate.java:40)
    at com.hp.hpl.jena.sparql.lang.UpdateParser.parse(UpdateParser.java:42)
    at com.hp.hpl.jena.update.UpdateFactory.make(UpdateFactory.java:90)
```

.........

Line 193 of the input file:
<edm:end rdf:datatype="http://www.w3.org/2001/XMLSchema#dateTime">1848-12-31T23:59:59/edm:end

**Comment by kba** [comment]
Line 193 is not related to the input file.

**Comment by kba** [comment]
The file in question contains

``` xml
<dm2e:mentioned>
   <foaf:Person rdf:about="http://data.dm2e.eu/data/agent/uber/dingler/Le&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;Duc">
      <skos:prefLabel xml:lang="de">Le
                            Duc</skos:prefLabel>
   </foaf:Person>
</dm2e:mentioned>
```

There should be neither newlines nor tabs in the URL. The validator could probably catch this, I just hadn't thought of that. In fact I'm surprised that Jena doesn't complain when parsing, only when creating a SPARQL Update from the serialized model.

**Comment by kba** [comment]
You can probably pre-process the file and replace all Tabs because they should never be significant in XML. Then It should be enough to make sure to replace all non-URI characters with something innocuous like underscore.

@ksdm2e You have similar data. Did you have to deal with this issue, maybe you can help out @JIwanowa.

**Comment by JIwanowa** [comment]
Thx!
