### ISSUE TITLE
Proposal for 1.1_Rev1.6: Strongly recommend setting a date associated for every CHO with displayLevel set to true

### ISSUE THREAD

**Issue by kba** [DM2E/dm2e-mappings#69]
For the search interface it is helpful to have a date for every CHO. Some currently have neither dcterms:created, dcterms:issued nor dcterms:temporal associated (e.g. http://data.dm2e.eu/data/html/resourcemap/gei/gei-digital/PPN618776001/20140301021526607).

Making this property strongly recommeded would mean that the validator would emit WARNING if a no date property is set. I am sure there are valid reasons for CHOs not having a date but it might also be a mapping oversight and a WARNING would make mappers aware of that.

**Comment by knepper** [comment]
This is a multivolume record with volumes that are issued at different times. The volumes have a dcterms:issued. The time difference in such cases might be 40 years or more if the volumes have seperate editions and it make limited sense to derive a time range for this record from the volumes.

However, +1

**Comment by ksdm2e** [comment]
Nice try! But I can assure you that dataprovider know data their data. If there were a date value, it would be mapped. There is no need for a WARNING.

**Comment by d0rg0ld** [comment]
Its a general question if and how data should be "inherited" to CHOs lower in the hierarchy. For example,  I see no need to store a date for each page CHO if a date valid for all pages can be found in an upperlevel CHO....

**Comment by kba** [comment]
I should add that I only mean CHOs for Aggregations that have dm2e:displayLevel set to true^^xsd:boolean.

@d0rg0ld: True, though in the case I mentioned it's the other way around. Nonetheless, if I come across examples for that, I will follow the dcterms:isPartOf property for dates.

@knepper I understand, that makes sense then for the example. Maybe we should generate (infer) a TimeSpan for CHOs that contain CHOs with a date, i.e. that it's existence began with the first issue? Or even create an open-ended timespan at mapping time?

Something like (not tested just an idea)

```
CONSTRUCT {
?cho dcterms:issued [
  edm:begin ?startDate.
]
} WHERE {
  SELECT (min(?issued) as ?startDate) WHERE {
    ?containedCHO dcterms:isPartOf ?cho .
    { ?containedCHO dcterms:issued ?issed . }
    UNION
    { ?containedCHO dcterms:issued ?timeSpan .
      ?timeSpan edm:begins ?issued  }
    FILTER(datatype(?timeSpan) = xsd:dateTime)
  }
}.
```

**Comment by knepper** [comment]
As I said: A TimeSpan could inferred or drived from the volumes. But it makes not too much sense if the volumes have several editions over 40 years or more.
In more common cases the edition is on the multivolume level and the multivolume record has a dcterms:issued.

However, in a time related search you will find the respective volumes, that's the main thing. They have dm2e:displayLevel also set to true. I suggest just to keep it as it is.

**Comment by kba** [comment]
In summary: Since the relationships between containing and contained CHO are too diverse, a generally correct inference rule would be too complex. Hence, CHOs with displayLevel true but without a date won't show up in date-filtered searches and will be sorted last in date-sorted queries. It is assumed that data mappers omit dates for a valid reason and not e.g. because of an oversight or because they don't know the date for sure.

So, I'll close this and we keep it as it is.

**Comment by d0rg0ld** [comment]
@kba : i would leave the "lower inherits date from upper" rule, I think this would be on the safe side - In the worst case it will be a broad timespan, but better than nothing
