### ISSUE TITLE
Missing Book type...

### ISSUE THREAD

**Issue by chrmor** [DM2E/dm2e-mappings#7]
http://data.dm2e.eu/data/html/resourcemap/uib/wab/Ms-114/1391118905391
there is no rdf:type that allows me to assume this is a Book and contains pages (perhaps Book was used as a type in other datasets).

**Comment by chrmor** [comment]
Any news on this issue?

**Comment by OyvindLGjesdal** [comment]
How about using dc:type "dm2e:Manuscript" as mentioned in 3.8 of the model? I will ask Alois which mappings to use here.

**Comment by kba** [comment]
@OyvindLGjesdal : Yes, something along the lines of

```
<http://data.dm2e.eu/data/item/uib/wab/Ms-XXXXXXX>
    rdf:type edm:ProvidedCHO ;
    dc:type dm2e:Manuscript .
```

Please get in touch when you have new data to validate/ingest.

**Comment by kba** [comment]
Fixed by newest ingest: http://data.dm2e.eu/data/html/resourcemap/uib/wab/Ms-114/20140306181642967 has dc:type dm2e:Manuscript
