### ISSUE TITLE
Empty rdf resource and about attributes

### ISSUE THREAD

**Issue by OyvindLGjesdal** [DM2E/dm2e-mappings#71]
http://example.com/relative/: 
    [FATAL]  is a relative URL used with property http://www.w3.org/1999/02/22-rdf-syntax-ns#type
    [FATAL]  is a relative URL used with property http://www.europeana.eu/schemas/edm/rights
    [FATAL]  is a relative URL used with property http://purl.org/dc/elements/1.1/format

**Comment by OyvindLGjesdal** [comment]
Corrected by adding the missing URLs to the TEI source files. Also added warning on transform if function fails to retrieve URL.

**Comment by kba** [comment]
> Hi Oyvind,
> 
> This is the base URI I set when parsing the RDF/XML.
> 
> this means that you have relative URIs in you RDF/XML data, most likely
> an attribute that should contain a URI but doesn't start with 'http://'.
> Most likely it's a WebResource that looks similar to the following in
> your data:
> 
> ```
> <edm:WebResource rdf:about="">
>   <dc:format>image/png</dc:format>
> </edm:WebResource
> ```
> 
> This was an issue for UBER/Dingler as well and since your data and
> mappings are similar (TEI / based on Kilian's mappings) you may want to
> ask them where it apears.
> 
> Good luck
> 
> Konstantin
