### ISSUE TITLE
Language Tags: Uses 'ger' instead of 'de'

### ISSUE THREAD

**Issue by kba** [DM2E/dm2e-mappings#72]
According to p.16 of the specs, 2-letter acronym is preferred when available. Jena also warns about that. The validator probably should, too.

**Comment by ksdm2e** [comment]
Could you give an exmaple. Might be ours.

**Comment by kba** [comment]
Just run the validator.

**Comment by ksdm2e** [comment]
That's useless: it might be the case, that you get different results due to different params or missing or old translation files. 

Thatswhy we all need an example.

**Comment by kba** [comment]
Ah, I see. Now I set DEF_LANGUAGE that fixed it I think
