### ISSUE TITLE
dc:subject must be a resource

### ISSUE THREAD

**Issue by kba** [DM2E/dm2e-mappings#73]
`dc:subject` must point to something of rdf:type skos:Concept, edm:Agent, edm:Place or edm:TimeSpan, not a Literal.

**Comment by ksdm2e** [comment]
Give always a sample, please!

**Comment by kba** [comment]
Fixed by EDM_RICH = true? can't find it now. These are the properties I use, is this correct?

```
DATAPROVIDER_ABB = bbaw
REPOSITORY_ABB = dta
TARGET_FORMAT = DM2E
TRANSFORMATION_DEPTH = PB
THE_DETAIL = Page
DEF_LANGUAGE = de
DEF_DCTYPE = Text
EDM_RICH = true
```

**Comment by ksdm2e** [comment]
yes, looks good. Thanks
