### ISSUE TITLE
Caret in URL in platen_oedipus

### ISSUE THREAD

**Issue by kba** [DM2E/dm2e-mappings#76]
The mapping `TEI2DM2E_xslt_20140227.zip` on this TEI http://www.deutschestextarchiv.de/book/download_xml/platen_oedipus_1829
generates a WebResource with URL `http://media.dwds.de/dta/images/platen_oedipus_1829/platen_oedipus_1829_^_1600px.jpg` which leads to the dataset not being ingested.

`^` is not a URL-safe character and must be URL-encoded. Since this is an external link, we either need to make the data provider aware of this issue so they fix it upstream or the mapping should omit this particular WebResource.

**Comment by ksdm2e** [comment]
It's in the data. Just ignore it.

I give that as feedback to the provider.

**Comment by kba** [comment]
I cannot ignore it, this is a FATAL error. Ingestion will break.

**Comment by ksdm2e** [comment]
That's right. If the ingestion breaks for this file, then it is an appropriate behaviour.

My suggestion is to ignore this file. We have no influence on contents and its only one (or some hundred) of 430000.

**Comment by kba** [comment]
Data Provider fixed this upstream IIRC -- @ksdm2e Can we close this?
