### ISSUE TITLE
URL-encoded slash in WebResource URL

### ISSUE THREAD

**Issue by kba** [DM2E/dm2e-mappings#77]
E.g. `http://data.dm2e.eu/data/concept/bbaw/dta/HERR%2F` in spener_piadesideria_1676.TEI-P5.xml

Happens in
- arnold_cyprian_1700.TEI-P5.xml
- arnold_ketzerhistorie02_1700.TEI-P5.xml 
- gressel_grabgedichte_1716.TEI-P5.xml
- naude_messkunst_1706.TEI-P5.xml
- spener_bedencken03_1702.TEI-P5.xml

and many more.

**Comment by ksdm2e** [comment]
Thanks for recognizing this. 

This is no problem: the concepts in bbaw/dta are candidates for processing with SILK and not reliable concepts. They can contain what-ever, random-like strings.

However, I can replace all reserved characters (for URL) in the next version of the script.

**Comment by ksdm2e** [comment]
fyi:

<pre>
   Example 2
   The URIs
    http://www.w3.org/albert/bertram/marie-claude
   and
   http://www.w3.org/albert/bertram%2Fmarie-claude
   are NOT identical, as in the second case the encoded slash does not have hierarchical significance.. 
</pre>

From http://www.w3.org/Addressing/URL/4_URI_Recommentations.html

I understand it in that way, that an encoded slash is ok. Just a comment:

**Comment by kba** [comment]
Yes, it is not a forbidden character per se, it's just that it breaks Pubby and is confusing.

**Comment by ksdm2e** [comment]
oh, pubby? really? my friend ...

I changed it in the recent version already: concepts with reserved characters should be omitted.

**Comment by kba** [comment]
Can't you just replace the reserved characters with something like underscore? You don't have that problem for any external URIs, just for those that you create yourself in the 'http://data.dm2e.eu/data/' namespace.

**Comment by ksdm2e** [comment]
It's ok. These concepts are only suggestions.

Thanks! afk for now!

**Comment by kba** [comment]
Still happens erbkam_tagebuch02_1843.TEI-P5.xml
