### ISSUE TITLE
[ERROR] INVALID_DATA_PROPERTY_RANGE http://purl.org/ontology/bibo/number

### ISSUE THREAD

**Issue by kba** [DM2E/dm2e-mappings#78]
bibo:number should be xsd:unsignedInt or untyped, not xsd:int.

**Comment by ksdm2e** [comment]
Yes. it is valid accorindg to Rev1.4.

**Comment by kba** [comment]
Yes. Can you make it valid with Rev1.5 and Rev1.6?

**Comment by ksdm2e** [comment]
And my script will be valid against rev1.6 again, when holdingInstitution asf is introduced.

The unsignedInt is fixed already. I am waiting for the specification (or did I miss the release?).

**Comment by kba** [comment]
holdingInstitution should be in Rev1.6-DRAFT already.

But good point about the specs. @edroege @JIwanowa Can you release Rev1.6 now?

**Comment by ksdm2e** [comment]
How can I check against Rev1.6? help message says only

```
-version <1.1_Rev1.2 | 1.1_Rev1.3 | 1.1_Rev1.4>
```

I hope I have the latest version ...

**Comment by kba** [comment]
You're way behind, download again. Always download the validator again before you validate, I fix things all the time. There's a has been a build time in the help output for the last 20 versions or so.

**Comment by ksdm2e** [comment]
Why should i update, when it's not finished.

did you change the download url?

**Comment by kba** [comment]
No, the download URI has always been the same.

What do you mean "not finished"? We're on a tight schedule, so please just update the validator regularly.

**Comment by ksdm2e** [comment]
Not finished, means not finished. 1.6 is stll a DRAFT.

Ok: tested some files 

 [ERROR]  has unknown property http://onto.dm2e.eu/schemas/dm2e/holdingInstitution

the rest seems ok.

**Comment by kba** [comment]
Yeah, the OWL file needs to be fixed. You're right. But once thatr's done it will validate. @edroege

**Comment by edroege** [comment]
Will release the 1.6 model specification and owl file today

**Comment by kba** [comment]
Should be up-to-date now, please re-download and re-validate and close if fixed.
