### ISSUE TITLE
wrong dc:format?

### ISSUE THREAD

**Issue by chrmor** [DM2E/dm2e-mappings#8]
http://data.dm2e.eu/data/rdf/resourcemap/uib/wab/Ms-114/Ms-114%2C145r%5B2%5Det145r%5B3%5D/1391118905391
here the format is a resource:
dc:format http://onto.dm2e.eu/schemas/dm2e/1.1/mime-types/text/html-named-content .
, while in other datasets a label was used (html-pundit-content). What is the correct value?

**Comment by JIwanowa** [comment]
Within DM2E dc:format has to be used only with a plain literal!

**Comment by knepper** [comment]
Wrong label -> Wittgenstein

**Comment by JIwanowa** [comment]
Oh, sorry! Is now labeled with wittgenstein.

**Comment by chrmor** [comment]
Any news? I guess the triple 

http://www.wittgensteinsource.org/Ms-114%2C145r%5B2%5Det145r%5B3%5D_n.html
      dc:format http://onto.dm2e.eu/schemas/dm2e/1.1/mime-types/text/html-named-content .

has to be replaced with something like:

http://www.wittgensteinsource.org/Ms-114%2C145r%5B2%5Det145r%5B3%5D_n.html
      dc:format "text/html-named-content" .

Please write here when fixed...

**Comment by OyvindLGjesdal** [comment]
dm2e-validate.jar does not report on this error. Fixed, will close when updated.

**Comment by kba** [comment]
> dm2e-validate.jar does not report on this error. 

Yes it does. Please download the latest version and check again. If it still doesn't report that as an error (SHOULD_BE_LITERAL, INVALID_DC_TYPE), open a new issue.

**Comment by OyvindLGjesdal** [comment]
[ERROR] SHOULD_BE_LITERAL   http://purl.org/dc/elements/1.1/format

**Comment by kba** [comment]
@OyvindLGjesdal: Right, so it correctly reports the error now?

**Comment by OyvindLGjesdal** [comment]
Yes I just didn't see the report for the error after removing the fatal one.

**Comment by kba** [comment]
@OyvindLGjesdal  Is a fatal error now, please update.
