### ISSUE TITLE
hasPart or isPartOf ?

### ISSUE THREAD

**Issue by chrmor** [DM2E/dm2e-mappings#80]
In the WAB dataset

http://data.dm2e.eu/data/html/resourcemap/uib/wab/Ts-310/20140306181642967

dcterms:hasPart relations are used

in other dataset the inverse (dcterms:isPartOf).

The meaning is the same but making data homogeneous would help consuming it.

**Comment by d0rg0ld** [comment]
@chrmor @OyvindLGjesdal We actually decided a while ago that we will only use isPartof -> From bottom to top, not the other way round. this is mentioned in the mapping recommendations

**Comment by kba** [comment]
Probably should go into the model that dcterms:hasPart is discouraged or even forbidden for CHOs. Then I can add that to the validator.

**Comment by OyvindLGjesdal** [comment]
New files with dcterms:isPartOf is ready to be ingested.

**Comment by OyvindLGjesdal** [comment]
Ingested on friday.

**Comment by kba** [comment]
Current version is http://data.dm2e.eu/data/html/dataset/uib/wab/20140311101616905.
