### ISSUE TITLE
An additional annotatable version fro images

### ISSUE THREAD

**Issue by chrmor** [DM2E/dm2e-mappings#81]
Would it be possible to have two annotatableversions, one for the image and one for the text?
The has been done in other datasets.
The image is already linked via the edm:object but I would need to have it linked via an additional asAnnotatableVersionOf and with correct dc:format "image/jpg"

Would it be possible asap? I'd like to show this dataset at the review.

**Comment by OyvindLGjesdal** [comment]
Do you want all images that a bemerkung is part of shown as hasAnnotatableVersion  dc:format "image/jpeg" or just the first like in edm:object?

**Comment by OyvindLGjesdal** [comment]
I've added the same image as edm:object to annotatable. More for later if needed.
