### ISSUE TITLE
Next and previous page inverted?

### ISSUE THREAD

**Issue by chrmor** [DM2E/dm2e-mappings#84]
Is it possible that previous and next pages are reversed?
Please check

**Comment by d0rg0ld** [comment]
Hi, isNextInSequence _always_ points to the _previous_ page 

Page2URI edm:isNextInSequence Page1URI

**Comment by OyvindLGjesdal** [comment]
Corrected. Will close when ingested.

**Comment by kba** [comment]
Fixed in http://data.dm2e.eu/data/html/dataset/uib/wab/20140311101616905
