### ISSUE TITLE
Why are some resources so slow?

### ISSUE THREAD

**Issue by chrmor** [DM2E/dm2e-mappings#85]
this one for example:

http://data.dm2e.eu/data/html/agent/ub-ffm/authority_gnd/118523708

or this one:

http://data.dm2e.eu/data/html/timespan/ub-ffm/1300-01-01T00-00-00_1399-12-31T23-59-59

please check.

**Comment by kba** [comment]
http://data.dm2e.eu/data/html/agent/ub-ffm/authority_gnd/118523708 :  96ms

http://data.dm2e.eu/data/html/timespan/ub-ffm/1300-01-01T00-00-00_1399-12-31T23-59-59 : 154 ms
