### ISSUE TITLE
Proposal for 1.2_Rev1.0: Enforce RFC 3986 compliant URIs

### ISSUE THREAD

**Issue by kba** [DM2E/dm2e-mappings#86]
Currently, the validator blacklists some characters in URLs. Ingestion problems have shown though that this is intrinsically flawed and leads to subtle errors where any part of the pipeline (validator, ingestion tool, triplestore, LD API, data consumers) can choke on malformed URIs.

Hence I propose to enforce the use of [RFC 3986](http://tools.ietf.org/html/rfc3986) compliant URIs by generating FATAL errors for invalid URIs at validation time. In summary, a character in the path part of an URI within DM2E must adhere to these conditions:
- no special treatment is necessary if it's an 
  - ASCII letter (`ABCDEFGHIJKLMNOPQRSTUVWYZabcdefghijklmnopqrstuvwxyz`)
  - a number (`0123456789`)
  - one of 
    - dash (`-`)
    - underscore (`_`)
    - dot (`.`)
    - tilde (`~`)
- if it is **anything other than  the aforementioned** it should be converted to Form-C UTF-8 and percent-encoded.

As an additional restriction, I propose to blacklist the following percent encoded characters for those URIs within our namespace (i.e. those starting with `http://data.dm2e.eu/data`:
- `%0A`/`%0D`/`%09` (newline, carriage return, tab -- this is most likely a mapping bug)
- `%2F` (slash -- while technically allowed, percent-encoded slashes lead to all kinds of trouble when transcoding URI)
- `%3C`/`%3E` (opening/closing bracket -- again, this might lead to trouble when transcoding using XML tools)

**Comment by ksdm2e** [comment]
ok. Because it is already a FATAL error.

Please provide also a consistent transaction and rollback strategy on triple, class and item level, at least in reporting.

**Comment by ksdm2e** [comment]
Please provide an example where Form-C UTF-8 is relevant in URLs.

**Comment by kba** [comment]
> ok. Because it is already a FATAL error.

No, just a few blacklisted character lead to FATAL errors.

> Please provide also a consistent transaction and rollback strategy on triple, class and item level, at least in reporting.

Please explain what you mean and how it relates to this issue.

> Please provide an example where Form-C UTF-8 is relevant in URLs.

Diacritics.

**Comment by edroege** [comment]
Currently, allowed characters are part of the mapping recommendations but we could also add a few words about allowed characters in the model specification. Apart from that, I think that this is a good suggestion.

**Comment by ksdm2e** [comment]
The mapping recommendations are the wrong place. It is a recommendation for the system-/db-/triplesore-administrators.

It is obvious that it's possible to break "any part of the pipeline (validator, ingestion tool, triplestore, LD API, data consumers)" by normal strings. Dataproviders do not know about such things and usually shouldn't care about id's in a target system - which are in our case URIs, which are also URLs.

It is definitely the duty of the system administrators to protect their systems. So it is up to them to correct subtly URIs according to their libraries and url-parsers. The addressee of the FATAL message is the ingesting, not the delivering application.

**Comment by kba** [comment]
> It is obvious that it's possible to break "any part of the pipeline (validator, ingestion tool, triplestore, LD API, data consumers)" by normal strings. Dataproviders do not know about such things and usually shouldn't care about id's in a target system - which are in our case URIs, which are also URLs.

URI is defined by RFC 3986. Everything that doesn't fit the first set of restrictions I proposed is not a URI. 

The restriction on URL-encoded slashes is just a sane thing to do because it can cause lots of problems. Sure, we can make Pubby work with them (and we will) but I still say they are problematic, just google for "URL-encoded slash server". If they are legacy URLs: fine: We'll have to live with that. But why willingly create such URLs that we know will cause problems? What's the benefit?

The retriction on forbidding URL-encoded ASCII control characters is just common sense, why would you want to use them?

**Comment by ksdm2e** [comment]
The above metioned proposal forces people (more than one) to implement workarounds for a problem, that they don't have. (btw: There is nothing wrong with encoded characters in URIs.)

But you can install one (1!) service at a certain point of your toolchain that makes proposed URIs appropriate to specific interpretations and implementations of uri-parsers for all dataproviders.

**Comment by kba** [comment]
> The above metioned proposal forces people (more than one) to implement workarounds for a problem, that they don't have

They might not have but data consumers will. Why deliberately cause problems?

> (btw: There is nothing wrong with encoded characters in URIs.)

Yes there is. While not illegal, some will cause problems for data consumers. Why do you need Tabs, Newlines and Carriage Returns in you URIs? Why can't you just replace the slash with something less problematic? I repeat from my proposal: These restrictions on url-encoded characters are only about URIs in our namespace, i.e. those that are created at mapping time, not legacy URIs by the providers that cannot be changed.

> But you can install one (1!) service at a certain point of your toolchain that makes proposed URIs appropriate to specific interpretations and implementations of uri-parsers for all dataproviders.

Please explain what you mean. You want a service in the toolchain (?) that changes URIs? How does that work? Should we change the providers' data? Could you provide a prototype of what you had in mind?

**Comment by ksdm2e** [comment]
> They might not have but data consumers will. Why deliberately cause problems?

If the data consumer knows, that he has problems due to his tools, then he has the responsibility to develop solutions for himself. He knows it best. Defensive programming was not invented yesterday.

> They are not illegal but they will cause problems for data consumers. 

I am happy, that we agree now, that the URIs are correct ("not illegal").

> These restrictions on url-encoded characters are only about URIs in our namespace,

The URIs are not an essential part of the dataproviders' metadata. I see no reason why it should not be possible to change them. 

> How does that work?

replace($myBadURI, $badCharacter, '_') . Or compute hashes ... I don't know the problems of your parser.

Generally, it is the duty or privilege of the harvester to provide or approve new identifers in its domain/architecture. But, the recommendations give this responsibility to the dataprovider. This discussion demonstrates clearly, that this assumption is too optimistic.

Dataproviders can only ensure, that identifiers are valid in their very own namespace during mapping time. In this sense, these URIs are just proposals.

**Comment by kba** [comment]
According to call on wednesday and as of 'Fri Apr 11 11:49:45 CEST 2014', validator will enforce the first part of the proposal (Non-RFC-3986-compliant URIs will result in FATAL) and emit WARNINGS for the second part of the proposal (URL-encoded one of `/`, `\n`, `\t`, `<`, `>`).
