### ISSUE TITLE
edm:TimeSpan vs. edm:timeSpan (non-capitalized)

### ISSUE THREAD

**Issue by kba** [DM2E/dm2e-mappings#90]
In Rara, timespans are typed as `edm:timeSpan` but should be typed `edm:TimeSpan` with a capital `T` and a capital `S`

**Comment by edroege** [comment]
To be precise, it should be `edm:TimeSpan` with capital `T` and `S` :)

**Comment by kba** [comment]
The DM2E-EDM conversion will correct this particular error but it's still an error and should be fixed.

**Comment by kba** [comment]
@kthth @jurzua Is this fixed?
