### ISSUE TITLE
Are there cases for skos:Concepts linked by owl:sameAs to non-GND, non-VIAF resources?

### ISSUE THREAD

**Issue by kba** [DM2E/dm2e-mappings#94]
The current DM2E->EDM algorithm directly links to contextual resources that reference GND or VIAF URIs via `owl:sameAs`. If a `skos:Concept` has `owl:sameAs` statements that point to neither GND nor VIAF, we need to change the `owl:sameAs` to `skos:exactMatch` to be compatible with Europeana's usage of SKOS.

This is implemented but I could not find any data to test. If any data provider has data like this:

```
... dc:subject <http://.../concept1> .
<http://.../concept1> a skos:Concept ;
    owl:sameAs <http://not.viaf.and.not.gnd.de/concept/foobar> ;
    skos:prefLabel "Foo Bar" .
```

Then please add a comment with a reference to the containing aggregation so we can test this.

**Comment by kba** [comment]
Here's one: http://data.dm2e.eu/data/html/concept/mpiwg/authority_lcsh/sh2008107595 in http://data.dm2e.eu/data/item/mpiwg/rara/MPIWG_S9DE5TWC

**Comment by knepper** [comment]
My mapping uses skos:exactMatch instead of owl:sameAs in skos:Concept but I think there is no real life example in the current data. It might be in GEI.

**Comment by knepper** [comment]
No occurence, corrected anyway...
