### ISSUE TITLE
DM2E Agent has no skos:prefLabel

### ISSUE THREAD

**Issue by kba** [DM2E/dm2e-mappings#96]
In UIB/WAB, e.g. http://data.dm2e.eu/data/html/resourcemap/uib/wab/Ms-114/20140311101616905, the `edm:provider` references `http://data.dm2e.eu/data/agent/DM2E` which has no skos:prefLabel.

**Comment by kba** [comment]
@OyvindLGjesdal It would be enough to add the statement
´´´
http://data.dm2e.eu/data/agent/DM2E skos:prefLabel "Digitised Manuscripts to Europeana".
´´´
to every file you produce.

**Comment by OyvindLGjesdal** [comment]
Added preflabel to all files for DM2EAgent.
