### ISSUE TITLE
Europeana can't handle datatypes

### ISSUE THREAD

**Issue by JIwanowa** [DM2E/dm2e-mappings#99]
rdf:datatype not allowed in dcterms:extent & rdf:datatype not allowed in dc:description

**Comment by kba** [comment]
For now, the best option is to not emit `rdf:datatypes` at all, sad though it is to impoverish the data.

I'll try to make that configurable so it can be turned off once Europeana can handle `rdf:datatype`.

**Comment by kba** [comment]
Fixed by https://github.com/DM2E/dm2e-ontologies/commit/ff78e102760575056b25fb3569d8df80417b8146.
